# Generated by Django 5.0.4 on 2024-04-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_name_order_product_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetables', 'Vegetables'), ('Bakery', 'Bakery'), ('Dairy', 'Dairy'), ('Snacks', 'Snacks'), ('Personal Care', 'Personal Care'), ('Household and Cleaning', 'Household and Cleaning'), ('Pet Care', 'Pet Care'), ('Electronics', 'Electronics'), ('Stationary', 'Stationary'), ('Miscellaneous', 'Miscellaneous')], max_length=50, null=True),
        ),
    ]
